### ISSUE TITLE
Convert name formatting to just #<badge> <lastname>

### ISSUE THREAD

**Issue by mpuckett159** [spdconvos/encryptedbot_py#28]
We don't really need first name here, this will save on characters for tweet length

**Comment by spdconvos** [comment]
I don't remember how the data that gets sent from the name sever is formatted, but go ahead. Should just need editing in this line: https://github.com/spdconvos/encryptedbot_py/blob/adebefd5b894278d88a67a5aa7ea079480403e9a/Bot.py#L259

**Comment by spdconvos** [comment]
Ok actually I'm fool, opening a PR for this
