### ISSUE TITLE
Long Calls Dropped

### ISSUE THREAD

**Issue by spdconvos** [spdconvos/encryptedbot_py#6]
Calls that are longer than the check interval never get returned. The beginning and end of a call both have to be within the check period to get counted. Increasing the check interval is a temporary mitigation that introduces some more latency and isn't flexible.

**Comment by AetherUnbound** [comment]
I was thinking something along the lines of:
* Keep track of existing encrypteds in a TTLCache (cachetools package is super good for this) or a deque (I think that exists in the collections stdlib package?) and check that cache on every API call, skip calls that already exist and add the new ones
* Tweet only the new calls
* Add some mechanism so the bot doesn't blurt out a bunch on startup if there are a number of recent calls

**Comment by spdconvos** [comment]
The OpenMHZ web app uses Socket.io to push updates to clients, maybe the bot could get a session going and get call data through that instead of API scraping.
